trusted_dns_servers:
  - 8.8.8.8      # Google DNS
  - 1.1.1.1      # Cloudflare DNS
  - 9.9.9.9      # Quad9 DNS
  - 208.67.222.222 # OpenDNS

check_interval: 300  # 5 minutes
log_file: "dns_spoof_log.txt"
monitored_domains:
  - google.com
  - facebook.com
  - youtube.com
  - amazon.com
  - twitter.com